In [3]:
import numpy as np #nump kütüphanesi np takma adı ile projeye dahil ediyoruz 

In [4]:
dizi=np.full((4,3),5)#5 sayısında oluşan 2*3 lük dizi
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [5]:
#yeni bir numpy dizisi oluşturuyoruz
np.array([1,2,3])

array([1, 2, 3])

In [6]:
#oluşturdugumuz diziyi bir degişken aktarıyoruz
dizi=np.array(["Elma","Erik","iğde"])

In [7]:
dizi

array(['Elma', 'Erik', 'iğde'], dtype='<U4')

In [11]:
dizi=np.array([1,2,3])
dizi

array([1, 2, 3])

In [12]:
dizi=np.array([1,2,3.14])
dizi

array([1.  , 2.  , 3.14])

In [13]:
dizi.dtype #dizinin degişken türünü verir.nump dizilerinde elemanların hepsi aynı türdendir

dtype('float64')

In [21]:
dizi=np.array([1,2,3,14], dtype=int)


In [22]:
dizi

array([ 1,  2,  3, 14])

**numpy ile farklı boyutlarda dizi oluşturma**

In [23]:
#bir boyuta dizi oluşturma
birboyut=np.array([1,2,3,4])
#iki boyut dizi oluşturma
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [24]:
birboyut

array([1, 2, 3, 4])

In [25]:
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Numpy yer tutucu**

In [26]:
np.zeros(7) #7 sıfırdan oluşan tek boyutlu dizi oluşturur.

array([0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros((2,3),dtype=int)#*sıfırdan olusan 2 boyutlu int dizi oluşturur.

array([[0, 0, 0],
       [0, 0, 0]])

In [28]:
np.ones(3)

array([1., 1., 1.])

In [29]:
np.full((4,3),5)#5 sayısında oluşan 2*3 lük dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [30]:
np.arange(2,22,5)#baslangıc bitiş ve artış degerlerine göre dizi oluşturma

array([ 2,  7, 12, 17])

In [31]:
np.linspace(2,10,num=7)#baslangıc bitiş ve artış belirtilen miktarda esit aralık

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [32]:
np.random.randint(0,10,5)#0-10 aralıgında rasgele 5 sayıdan oluşan bir boyutlu dizi

array([0, 1, 5, 6, 5])

In [33]:
np.random.randint(0,10,(5,2))#0-10 aralıgında 5*2 rasgele sayılardan oluşan bir boyutlu diz

array([[7, 9],
       [9, 3],
       [6, 5],
       [4, 3],
       [3, 3]])

**Diziler ile ilgili işlemler**

In [34]:
#dizilerin eleman sayısını ögrenmek için shape komutu kullanılır
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
dizi.shape

(3, 4)

In [35]:
#ndim dizi boyutunu ögrenmek için kullanılır
dizi.ndim

2

In [36]:
#size dizideki toplam eleman sayısını gösterir
dizi.size

12

In [37]:
dizi.itemsize #dizideki her bir elemanın bayt cinsinde degerini verir

4