In [6]:
import numpy as np #numpy kütüphanesini np olarak ekler
dizi=np.array([1,2,3]) #numpy dizisi oluşturur
dizi=np.array(["armut"",cilek","seftali"]) #numpy dizisini atama işlemi yapar
dizi=np.array([1,2,3,],dtype=int) #değerlerini içeren bir dizi oluşturur
dizi #dizilerin avantıjı içindeki verilere göre kendisi tek tip olarak ayarlanması


array([1, 2, 3])

In [7]:
dizi2

array(['armut,cilek', 'seftali'], dtype='<U11')

In [8]:
dizi3

array([1, 2, 3, 3])

In [10]:
birboyut=np.array([1,2,3])


In [11]:
birboyut

array([1, 2, 3])

In [12]:
ikiboyut = np.array([[1,2,3], [4,5,6]])

In [13]:
ikiboyut

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
ucboyut= np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

In [15]:
ucboyut

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])